# Pandas I

<a id="section_toc"></a> 
## Tabla de Contenidos

[Intro](#section_intro)

[Series](#section_series)

$\hspace{.5cm}$[1. `Series` como generalización de un array de NumPy](#section_series_array_numpy)

$\hspace{.5cm}$[2. `Series` como un `dict` especializado](#section_series_dict)

[Constructor](#section_constructor)

[Selección de datos en Series](#section_selection)

[Reindexing](#section_reindexing)

[Indexers: loc e iloc](#section_loc_iloc)

---


## Series

<a id="section_intro"></a> 
###  Intro
[volver a TOC](#section_toc)


#### Documentación 
https://pandas.pydata.org/pandas-docs/stable/reference/series.html

Una Series es un objeto similar a un vector **unidimensional**. 

Contiene un **array de valores** (que en este caso son Perro, Oso, Jirafa, ...) y un **array de etiquetas** asociados a estos valores **denominado índice** (que en este caso son numéricos: 0, 1, 2, ...).

Cuando no especificamos un índice para los datos, se asigna por default un índice formado por valores enteros de 0 a N-1, donde N es la cantidad de valores en la serie.

Los valores de la serie pueden ser de cualquier tipo de datos, pero todos **los valores de una serie deben coincidir en su tipo**.

Las etiquetas, además de numéricas, también pueden ser de tipo cadena de caracteres.

Una Serie también puede pensarse como un **diccionario de tamaño fijo** con sus claves numéricas (Index) ordenadas.

Al igual que  los arrays de NumPy, permiten pasar una **lista de elementos (índices) para seleccionar un subconjunto** de valores.

![Image](img/serie.jpg)



In [1]:
import numpy as np
import pandas as pd

<a id="section_series"></a> 
## Objetos `Series` en Pandas
[volver a TOC](#section_toc)

* Puede pensarse como una array de una sola dimensión indexado. 
* Puede ser creado desde una lista:

In [44]:
lista = [0.25, 0.5, 0.75, 1.0]


data = pd.Series(lista)
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [45]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

Los valores de la serie se obtienen con:

In [47]:
na=data.values

In [49]:
type(data)

pandas.core.series.Series

El índice de la serie se obtiene con:

In [5]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [52]:
data.index[2]

2

Podemos acceder a los valores de los elementos de una serie usando el índice asociado a esos elementos, de forma similar a los arrays de Numpy: con los `[]`

In [53]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [54]:
data[2]

0.75

In [58]:
data[0:3]

0    0.25
1    0.50
2    0.75
dtype: float64

In [63]:
data[0:3].values.mean()

0.5

---

# Puedo poner el indice que yo quiera?

<a id="section_series_array_numpy"></a> 
### `Series` como generalización de un array de NumPy 
[volver a TOC](#section_toc)


* La diferencia esencial con un array de Numpy es que el array tiene un índice entero *implícitamente definido*, mientras que un objeto `Series` de Pandas tiene un índice asociado a los valores *que está definido de forma explícita*.

* El índice explícito no tiene por qué ser de tipo entero y **sus valores pueden no ser únicos**, es decir tener repeticiones.


Creemos una instancia de `Series`:

In [66]:
valores =   [0.25, 0.5 , 0.75, 1.0]


etiquetas = ['a' , 'b' , 'c' , 'd']

etiquetas_num = [2, 5, 3, 1]



data1 = pd.Series(valores, index=etiquetas)



data2 = pd.Series(valores, index=etiquetas_num)

print(data1)


a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64


In [10]:
print(data2)


2    0.25
5    0.50
3    0.75
1    1.00
dtype: float64


Miremos el valor del segundo elemento usando su etiqueta:

In [68]:
print(data1['b'])
print(data2[5])

0.25


KeyError: 0

Y repitamos usando su posición:

In [12]:
print(data1[1])
print(data2[1])

0.5
1.0


Esperábamos que `print(data2[1])`devolviera `0.50` que es el segundo elementos de data2

<div id="caja2" style="float:left;width: 100%;">
  <div style="float:left;width: 15%;"></div>
  <div style="float:left;width: 85%;"><label>
      <label>¿Qué pasó? ¿Qué hicimos mal? ¿Cómo se resuelve este problema? </label></div>
</div>

### Pandas interpreto el indice literalemente, por default hace loc

Vamos a ver ahora las properties `loc` e `iloc`

`iloc` recibe como parámetro la posición y `loc` recibe como parámetro la etiqueta

Como ayuda memoria pensemos `iloc` como integer-location: indexamos con enteros que representan la posición.

Vamos a ver entonces qué obtenemos como segundo elemento con estas properties:

In [69]:
print(data1.iloc[0])
print(data2.iloc[0])

0.25
0.25


In [14]:
print(data1.loc['b'])
print(data2.loc[5])

0.5
0.5


---

<a id="section_series_dict"></a> 
### `Series` como un `dict` especializado
[volver a TOC](#section_toc)

Un `dict` es una estructura de datos que mapea un conjunto de keys arbitrarias a un conjunto de valores.

La analogía entre una instancia de `Series` y una de `dict` es inmediata. Puede crearse una instancia de `Series` a partir de un `dict` donde las keys del diccionario serán el índice de la instancia de Series.


In [71]:
population_dict = {'California': 38332521,
                                      'New York': 19651127,
                   'Florida': 19552860,
                   'Texas': 26448193,

                   'Illinois': 12882135}





population = pd.Series(population_dict)

In [78]:
population_dict.values()

dict_values([38332521, 19651127, 19552860, 26448193, 12882135])

In [72]:
population

California    38332521
New York      19651127
Florida       19552860
Texas         26448193
Illinois      12882135
dtype: int64

In [15]:
print('instancia de diccionario: ')
print(population_dict)
print('---')
print('instancia de series: ')
print(population)

instancia de diccionario: 
{'California': 38332521, 'Texas': 26448193, 'New York': 19651127, 'Florida': 19552860, 'Illinois': 12882135}
---
instancia de series: 
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64


Miramos el valor de población en California con la misma sintaxis para `Series` y `dict`:

In [16]:
print(population['California'])
print(population_dict['California'])

38332521
38332521


A diferencia de un `dict` una instancia de `Series` soporta algunas operaciones del estilo de un numpy array como, por ejemplo, slicing. 

<div id="caja3" style="float:left;width: 100%;">
  <div style="float:left;width: 15%;"><img src="../../../common/icons/para_seguir_pensando.png" style="align:left"/> </div>
  <div style="float:left;width: 85%;"><label>
      <label>¿Recuerdan qué pasa con los límites en slicing en arrays?</label></div>
</div>


Veamos un ejemplo de slicing en una instancia de Series (notar que en este caso el endpoint es inclusivo):   

In [76]:
population

California    38332521
New York      19651127
Florida       19552860
Texas         26448193
Illinois      12882135
dtype: int64

In [75]:
population.index

Index(['California', 'New York', 'Florida', 'Texas', 'Illinois'], dtype='object')

In [85]:
population['California':'Florida']

California    38332521
New York      19651127
Florida       19552860
dtype: int64

Si usamos el index implícito, el endpoint **no** se incluye en el slicing:

In [83]:
population.iloc[0:3]

California    38332521
New York      19651127
Florida       19552860
dtype: int64

Otro ejemplo:

In [19]:
states_list = ['Illinois','Texas','New York', 'Florida', 'California']
states_pop = [12882135, 26448193, 19651127, 19552860, 38332521]



states = pd.Series(states_pop, index= states_list)


states['Illinois':'New York']

Illinois    12882135
Texas       26448193
New York    19651127
dtype: int64

---

<a id="section_constructor"></a> 
## Constructor
[volver a TOC](#section_toc)

#### Documentación 
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html

Podemos construir instancias de `Series` a partir de:

1) una lista o un array de `Numpy`:

In [20]:
pd.Series([2, 4, 6]) 

0    2
1    4
2    6
dtype: int64

2) un escalar repetido a lo largo de un índice:

In [87]:
pd.Series(0, index = [100, 200, 300]) 

100    0
200    0
300    0
dtype: int64

3) un diccionario:

In [22]:
pd.Series({2:'a', 1:'b', 3:'c'}) 

2    a
1    b
3    c
dtype: object

Y en todos los casos podría usarse un índice explícitamente definido:

In [88]:
pd.Series([2, 4, 6], index=[3, 2, 2])

3    2
2    4
2    6
dtype: int64

In [95]:
pd.Series([2, 4, 6], index=[3, 2, 2]).loc[2]

2    4
2    6
dtype: int64

<div id="caja3" style="float:left;width: 100%;">
  <div style="float:left;width: 15%;"><img src="../../../common/icons/para_seguir_pensando.png" style="align:left"/> </div>
  <div style="float:left;width: 85%;"><label>
      <label>¿Cuántos elementos obtengo si indexo este objeto con el índice 2?</label></div>
</div>



In [97]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2, 2, 2, 2, 3, 1]) 

3    c
2    a
2    a
2    a
2    a
3    c
1    b
dtype: object

---

<a id="section_selection"></a> 
## Selección de datos en Series
[volver a TOC](#section_toc)

Vamos a ver ahora distintas formas de seleccionar elementos en instancias de `Series`

Comencemos creando el objeto `data`:

In [101]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

### `Series` como diccionarios

Si pensamos a las instancias de `Series` como diccionarios, podemos usar expresiones similares a las usadas en dicts para examinar keys y valores:

In [98]:
data.name

In [26]:
'b' in data

True

In [27]:
0.5 in data

False

In [28]:
0.5 in data.values

True

**'b' in data** es equivalente a **'b' in data.keys()**:

In [29]:
'b' in data.keys()

True

In [30]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

**data.keys()** es equivalente a **data.index**:

In [31]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [32]:
data.keys() is data.index

True

In [104]:
type(data.items())

zip

In [103]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

Como en un diccionario, podemos extender una instancia de Series definiendo una nueva key y asignarle un nuevo valor:

In [108]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [109]:
data['e']

1.25

In [119]:
data['f']=23423

In [131]:
u=[]


In [133]:
u.append(6)

In [134]:
u

[6]

In [125]:
data=data.append(pd.Series([ 22534645], index=['f']))

In [126]:
data.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'f'], dtype='object')

### `Series` como array de una dimensión

Una instancia de `Series` provee una forma de seleccionar datos análoga a la de arrays. Podemos usar _slices_, _masking_ y _fancy indexing_.

#### Slicing explícito

Cuando hacemos slicing explícito (`data['a':'c']`) el índice final es incluido en el slice


In [35]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

#### Slicing implícito por posición (enteros)

Cuando hacemos slicing implícto (`data[0:2]`) el índice final **NO** es incluido en el slice

In [36]:
data[0:2]

a    0.25
b    0.50
dtype: float64

#### Boolean masking:

In [37]:
data[ (data > 0.3) & (data < 0.8)   ]

b    0.50
c    0.75
dtype: float64

#### Fancy indexing:

In [139]:
data.sort_index()

a       32534.00
b           0.50
c           0.75
d           1.00
e           1.25
f       23423.00
f    22534645.00
dtype: float64

In [135]:
data[[0, 3, 2, 1]]

a    32534.00
d        1.00
c        0.75
b        0.50
dtype: float64

In [145]:
a = np.array([[0.1, .32, .2,  0.4, 0.8], 
             [.23, .18, .56, .61, .12], 
             [.9,   .3,  .6,  .5,  .3],  
             [.34, .75, .91, .19, .21]]) 
a

array([[0.1 , 0.32, 0.2 , 0.4 , 0.8 ],
       [0.23, 0.18, 0.56, 0.61, 0.12],
       [0.9 , 0.3 , 0.6 , 0.5 , 0.3 ],
       [0.34, 0.75, 0.91, 0.19, 0.21]])

In [148]:
a.T

array([[0.1 , 0.23, 0.9 , 0.34],
       [0.32, 0.18, 0.3 , 0.75],
       [0.2 , 0.56, 0.6 , 0.91],
       [0.4 , 0.61, 0.5 , 0.19],
       [0.8 , 0.12, 0.3 , 0.21]])

In [146]:
print(np.corrcoef(a))

[[ 1.         -0.35153114 -0.74736506 -0.48917666]
 [-0.35153114  1.          0.23810227  0.15958285]
 [-0.74736506  0.23810227  1.         -0.03960706]
 [-0.48917666  0.15958285 -0.03960706  1.        ]]


In [147]:
print(np.corrcoef(a.T))

[[ 1.         -0.03783885  0.34905716  0.14648975 -0.34945863]
 [-0.03783885  1.          0.67888519 -0.96102583 -0.12757741]
 [ 0.34905716  0.67888519  1.         -0.45104803 -0.80429469]
 [ 0.14648975 -0.96102583 -0.45104803  1.         -0.15132323]
 [-0.34945863 -0.12757741 -0.80429469 -0.15132323  1.        ]]
